# Site setings
name: 'Huy-Dung NGUYEN'
description: 'AI Developer'
meta_description: 'AI Blogger'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'authorimage.jpg'
  greetings: "Hi there! My name is Huy-Dung NGUYEN. I'm a PhD in Mediacal Image Processing using Deep Learning at University of Bordeaux, France. It’s nice to meet you."
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://huydung179.github.io
disqus: 'justgoodthemes'
mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
# Add your GA Tracking Id
ga_analytics: 

# Contact form setings
email: huydung.ng.179@gmail.com
contact_page_description: "Not implemented."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
# twitter: 'justgoodthemes'
facebook: 'hdung95'
github: 'huydung179'
# codepen: 'username'
# dribbble: 'username'
# medium: '@username'
# instagram: 'username'
# pinterest: 'username'
linkedin: 'huydungnguyen'
# producthunt: '@username'
# quora: 'username'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Contact Me
    url: /contact
  - text: Search
    url: /search

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
